// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/api.proto

package apiproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommonRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRsp) Reset()         { *m = CommonRsp{} }
func (m *CommonRsp) String() string { return proto.CompactTextString(m) }
func (*CommonRsp) ProtoMessage()    {}
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{0}
}

func (m *CommonRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRsp.Unmarshal(m, b)
}
func (m *CommonRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRsp.Marshal(b, m, deterministic)
}
func (m *CommonRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRsp.Merge(m, src)
}
func (m *CommonRsp) XXX_Size() int {
	return xxx_messageInfo_CommonRsp.Size(m)
}
func (m *CommonRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRsp proto.InternalMessageInfo

func (m *CommonRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CommonRsp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type GetUserInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{1}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserInfoRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *Person  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRsp) Reset()         { *m = GetUserInfoRsp{} }
func (m *GetUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRsp) ProtoMessage()    {}
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{2}
}

func (m *GetUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRsp.Unmarshal(m, b)
}
func (m *GetUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRsp.Merge(m, src)
}
func (m *GetUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRsp.Size(m)
}
func (m *GetUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRsp proto.InternalMessageInfo

func (m *GetUserInfoRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUserInfoRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetUserInfoRsp) GetData() *Person {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAllUserInfoReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUserInfoReq) Reset()         { *m = GetAllUserInfoReq{} }
func (m *GetAllUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAllUserInfoReq) ProtoMessage()    {}
func (*GetAllUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{3}
}

func (m *GetAllUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserInfoReq.Unmarshal(m, b)
}
func (m *GetAllUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetAllUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserInfoReq.Merge(m, src)
}
func (m *GetAllUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetAllUserInfoReq.Size(m)
}
func (m *GetAllUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserInfoReq proto.InternalMessageInfo

func (m *GetAllUserInfoReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetAllUserInfoReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetAllUserInfoRsp struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *AllPerson `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllUserInfoRsp) Reset()         { *m = GetAllUserInfoRsp{} }
func (m *GetAllUserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetAllUserInfoRsp) ProtoMessage()    {}
func (*GetAllUserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{4}
}

func (m *GetAllUserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUserInfoRsp.Unmarshal(m, b)
}
func (m *GetAllUserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUserInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetAllUserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUserInfoRsp.Merge(m, src)
}
func (m *GetAllUserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetAllUserInfoRsp.Size(m)
}
func (m *GetAllUserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUserInfoRsp proto.InternalMessageInfo

func (m *GetAllUserInfoRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAllUserInfoRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAllUserInfoRsp) GetData() *AllPerson {
	if m != nil {
		return m.Data
	}
	return nil
}

type PingChatReq struct {
	InputParam           *PingReq `protobuf:"bytes,3,opt,name=inputParam,proto3" json:"inputParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingChatReq) Reset()         { *m = PingChatReq{} }
func (m *PingChatReq) String() string { return proto.CompactTextString(m) }
func (*PingChatReq) ProtoMessage()    {}
func (*PingChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{5}
}

func (m *PingChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingChatReq.Unmarshal(m, b)
}
func (m *PingChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingChatReq.Marshal(b, m, deterministic)
}
func (m *PingChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingChatReq.Merge(m, src)
}
func (m *PingChatReq) XXX_Size() int {
	return xxx_messageInfo_PingChatReq.Size(m)
}
func (m *PingChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingChatReq proto.InternalMessageInfo

func (m *PingChatReq) GetInputParam() *PingReq {
	if m != nil {
		return m.InputParam
	}
	return nil
}

type PongChatRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *PongRsp `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongChatRsp) Reset()         { *m = PongChatRsp{} }
func (m *PongChatRsp) String() string { return proto.CompactTextString(m) }
func (*PongChatRsp) ProtoMessage()    {}
func (*PongChatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecf0878b123623e2, []int{6}
}

func (m *PongChatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongChatRsp.Unmarshal(m, b)
}
func (m *PongChatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongChatRsp.Marshal(b, m, deterministic)
}
func (m *PongChatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongChatRsp.Merge(m, src)
}
func (m *PongChatRsp) XXX_Size() int {
	return xxx_messageInfo_PongChatRsp.Size(m)
}
func (m *PongChatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PongChatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PongChatRsp proto.InternalMessageInfo

func (m *PongChatRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PongChatRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PongChatRsp) GetData() *PongRsp {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonRsp)(nil), "apiproto.CommonRsp")
	proto.RegisterType((*GetUserInfoReq)(nil), "apiproto.getUserInfoReq")
	proto.RegisterType((*GetUserInfoRsp)(nil), "apiproto.getUserInfoRsp")
	proto.RegisterType((*GetAllUserInfoReq)(nil), "apiproto.getAllUserInfoReq")
	proto.RegisterType((*GetAllUserInfoRsp)(nil), "apiproto.getAllUserInfoRsp")
	proto.RegisterType((*PingChatReq)(nil), "apiproto.pingChatReq")
	proto.RegisterType((*PongChatRsp)(nil), "apiproto.pongChatRsp")
}

func init() { proto.RegisterFile("proto/api.proto", fileDescriptor_ecf0878b123623e2) }

var fileDescriptor_ecf0878b123623e2 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x57, 0xf7, 0x83, 0xed, 0x15, 0x74, 0x0b, 0x2a, 0xa5, 0x5e, 0x46, 0x51, 0xe8, 0x69,
	0xe2, 0xbc, 0xe9, 0xc5, 0x31, 0x3c, 0x08, 0x1e, 0x46, 0xc4, 0x8b, 0x08, 0x12, 0xb7, 0x18, 0x03,
	0x6d, 0x92, 0x35, 0x9d, 0x07, 0xff, 0x55, 0xff, 0x19, 0x49, 0xda, 0xd9, 0x04, 0x19, 0xec, 0xf6,
	0xed, 0xf7, 0xfd, 0xfa, 0xe4, 0xbd, 0xc2, 0x91, 0x2a, 0x64, 0x29, 0x2f, 0x89, 0xe2, 0x13, 0xab,
	0x50, 0x9f, 0x28, 0x6e, 0x55, 0x8c, 0xaa, 0x90, 0xa2, 0x85, 0x96, 0xa2, 0x8a, 0xc6, 0xc3, 0xda,
	0xe3, 0x82, 0x55, 0x4e, 0x72, 0x0f, 0x83, 0xb9, 0xcc, 0x73, 0x29, 0xb0, 0x56, 0x08, 0x41, 0x67,
	0x29, 0x57, 0x34, 0x0a, 0xc6, 0x41, 0xda, 0xc5, 0x56, 0xa3, 0x21, 0xb4, 0x73, 0xcd, 0xa2, 0x83,
	0x71, 0x90, 0x0e, 0xb0, 0x91, 0x26, 0x6b, 0x45, 0x4a, 0x12, 0xb5, 0xad, 0x65, 0x75, 0x92, 0xc2,
	0x21, 0xa3, 0xe5, 0xb3, 0xa6, 0xc5, 0x83, 0xf8, 0x90, 0x98, 0xae, 0xd1, 0x29, 0xf4, 0x36, 0xe6,
	0x73, 0x65, 0xbb, 0x0d, 0x70, 0xfd, 0x95, 0xbc, 0xfa, 0x99, 0x7b, 0x4f, 0x3d, 0x77, 0xa6, 0x86,
	0xd3, 0xe1, 0x64, 0xfb, 0xce, 0x49, 0xf5, 0xc0, 0x9a, 0xe3, 0x16, 0x46, 0x8c, 0x96, 0xb3, 0x2c,
	0x73, 0x51, 0x10, 0x74, 0x14, 0x61, 0x7f, 0x03, 0x8c, 0x36, 0x9e, 0xe6, 0xdf, 0xd4, 0x4e, 0xe8,
	0x62, 0xab, 0x93, 0xe5, 0xbf, 0xe2, 0xbd, 0xe9, 0x52, 0x8f, 0xee, 0xb8, 0xa1, 0x23, 0x59, 0xf6,
	0xe6, 0x11, 0xde, 0x41, 0x68, 0xd6, 0x3f, 0xff, 0x24, 0xa5, 0x61, 0xbb, 0x02, 0xe0, 0x42, 0x6d,
	0xca, 0x05, 0x29, 0x48, 0x5e, 0x97, 0x8f, 0x9a, 0xf2, 0x05, 0x17, 0x0c, 0xd3, 0x35, 0x76, 0x92,
	0x92, 0x17, 0x08, 0x95, 0xac, 0x3b, 0xec, 0x0d, 0x78, 0xe1, 0x01, 0xba, 0x13, 0xa4, 0x60, 0x58,
	0xab, 0x8a, 0x6e, 0xfa, 0x13, 0x00, 0xcc, 0x14, 0x7f, 0xa2, 0xc5, 0x17, 0x5f, 0x52, 0x34, 0x87,
	0xd0, 0x39, 0x16, 0x8a, 0x9a, 0x32, 0xff, 0xda, 0xf1, 0x8e, 0x88, 0x56, 0x49, 0x0b, 0x3d, 0xda,
	0x8b, 0x3b, 0x6b, 0x45, 0x67, 0x5e, 0xb6, 0x7f, 0xad, 0x78, 0x77, 0xd0, 0x76, 0xbb, 0x81, 0xfe,
	0x76, 0x7f, 0xe8, 0xc4, 0xf9, 0x0b, 0x9a, 0x9d, 0xc6, 0xae, 0xdd, 0x2c, 0x2a, 0x69, 0xbd, 0xf7,
	0xac, 0x79, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x14, 0x53, 0xf8, 0x92, 0x36, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error)
	GetAllUserInfo(ctx context.Context, in *GetAllUserInfoReq, opts ...grpc.CallOption) (*GetAllUserInfoRsp, error)
	PingChat(ctx context.Context, in *PingChatReq, opts ...grpc.CallOption) (*PongChatRsp, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRsp, error) {
	out := new(GetUserInfoRsp)
	err := c.cc.Invoke(ctx, "/apiproto.ApiService/getUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetAllUserInfo(ctx context.Context, in *GetAllUserInfoReq, opts ...grpc.CallOption) (*GetAllUserInfoRsp, error) {
	out := new(GetAllUserInfoRsp)
	err := c.cc.Invoke(ctx, "/apiproto.ApiService/getAllUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) PingChat(ctx context.Context, in *PingChatReq, opts ...grpc.CallOption) (*PongChatRsp, error) {
	out := new(PongChatRsp)
	err := c.cc.Invoke(ctx, "/apiproto.ApiService/pingChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
type ApiServiceServer interface {
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoRsp, error)
	GetAllUserInfo(context.Context, *GetAllUserInfoReq) (*GetAllUserInfoRsp, error)
	PingChat(context.Context, *PingChatReq) (*PongChatRsp, error)
}

// UnimplementedApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedApiServiceServer struct {
}

func (*UnimplementedApiServiceServer) GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedApiServiceServer) GetAllUserInfo(ctx context.Context, req *GetAllUserInfoReq) (*GetAllUserInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserInfo not implemented")
}
func (*UnimplementedApiServiceServer) PingChat(ctx context.Context, req *PingChatReq) (*PongChatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingChat not implemented")
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiproto.ApiService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetAllUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetAllUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiproto.ApiService/GetAllUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetAllUserInfo(ctx, req.(*GetAllUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_PingChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).PingChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiproto.ApiService/PingChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).PingChat(ctx, req.(*PingChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiproto.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUserInfo",
			Handler:    _ApiService_GetUserInfo_Handler,
		},
		{
			MethodName: "getAllUserInfo",
			Handler:    _ApiService_GetAllUserInfo_Handler,
		},
		{
			MethodName: "pingChat",
			Handler:    _ApiService_PingChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
