// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ping.proto

package apiproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//ping request param
type PingReq struct {
	Fid                  int32    `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Fname                string   `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	Tid                  int32    `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	Tname                string   `protobuf:"bytes,4,opt,name=tname,proto3" json:"tname,omitempty"`
	Ping                 string   `protobuf:"bytes,5,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_152de50a8b8a7ed0, []int{0}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *PingReq) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *PingReq) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *PingReq) GetTname() string {
	if m != nil {
		return m.Tname
	}
	return ""
}

func (m *PingReq) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

//pong response param
type PongRsp struct {
	Fid                  int32    `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Fname                string   `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	Tid                  int32    `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	Tname                string   `protobuf:"bytes,4,opt,name=tname,proto3" json:"tname,omitempty"`
	Pong                 string   `protobuf:"bytes,5,opt,name=pong,proto3" json:"pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongRsp) Reset()         { *m = PongRsp{} }
func (m *PongRsp) String() string { return proto.CompactTextString(m) }
func (*PongRsp) ProtoMessage()    {}
func (*PongRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_152de50a8b8a7ed0, []int{1}
}

func (m *PongRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongRsp.Unmarshal(m, b)
}
func (m *PongRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongRsp.Marshal(b, m, deterministic)
}
func (m *PongRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongRsp.Merge(m, src)
}
func (m *PongRsp) XXX_Size() int {
	return xxx_messageInfo_PongRsp.Size(m)
}
func (m *PongRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PongRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PongRsp proto.InternalMessageInfo

func (m *PongRsp) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *PongRsp) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *PongRsp) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *PongRsp) GetTname() string {
	if m != nil {
		return m.Tname
	}
	return ""
}

func (m *PongRsp) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

func init() {
	proto.RegisterType((*PingReq)(nil), "apiproto.PingReq")
	proto.RegisterType((*PongRsp)(nil), "apiproto.PongRsp")
}

func init() { proto.RegisterFile("proto/ping.proto", fileDescriptor_152de50a8b8a7ed0) }

var fileDescriptor_152de50a8b8a7ed0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc8, 0xcc, 0x4b, 0xd7, 0x03, 0x33, 0x85, 0x38, 0x12, 0x0b, 0x32, 0xc1, 0x2c,
	0xa5, 0x5c, 0x2e, 0xf6, 0x80, 0xcc, 0xbc, 0xf4, 0xa0, 0xd4, 0x42, 0x21, 0x01, 0x2e, 0xe6, 0xb4,
	0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0x35, 0x2d,
	0x2f, 0x31, 0x37, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x01, 0xa9, 0x2b, 0xc9,
	0x4c, 0x91, 0x60, 0x86, 0xa8, 0x2b, 0x81, 0xa8, 0x2b, 0x01, 0xab, 0x63, 0x81, 0xa8, 0x03, 0x73,
	0x84, 0x84, 0xb8, 0x58, 0x40, 0x56, 0x4a, 0xb0, 0x82, 0x05, 0xc1, 0x6c, 0xb0, 0x75, 0xf9, 0x79,
	0xe9, 0x41, 0xc5, 0x05, 0x34, 0xb1, 0x2e, 0x1f, 0xc9, 0xba, 0xfc, 0xbc, 0xf4, 0x24, 0x36, 0xb0,
	0x27, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x53, 0x51, 0xb0, 0x02, 0x01, 0x00, 0x00,
}
