// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/person.proto

package apiproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type AllPerson struct {
	Per                  []*Person `protobuf:"bytes,1,rep,name=Per,proto3" json:"Per,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPerson) Reset()         { *m = AllPerson{} }
func (m *AllPerson) String() string { return proto.CompactTextString(m) }
func (*AllPerson) ProtoMessage()    {}
func (*AllPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_d96e036db946e632, []int{1}
}

func (m *AllPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPerson.Unmarshal(m, b)
}
func (m *AllPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPerson.Marshal(b, m, deterministic)
}
func (m *AllPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPerson.Merge(m, src)
}
func (m *AllPerson) XXX_Size() int {
	return xxx_messageInfo_AllPerson.Size(m)
}
func (m *AllPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPerson.DiscardUnknown(m)
}

var xxx_messageInfo_AllPerson proto.InternalMessageInfo

func (m *AllPerson) GetPer() []*Person {
	if m != nil {
		return m.Per
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "apiproto.person")
	proto.RegisterType((*AllPerson)(nil), "apiproto.all_person")
}

func init() { proto.RegisterFile("proto/person.proto", fileDescriptor_d96e036db946e632) }

var fileDescriptor_d96e036db946e632 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x03, 0x73, 0x84, 0x38, 0x12, 0x0b, 0x32,
	0xc1, 0x2c, 0x25, 0x3b, 0x2e, 0x36, 0x88, 0x8c, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa,
	0x04, 0x13, 0x58, 0x04, 0xcc, 0x16, 0x12, 0xe0, 0x62, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x0d, 0x02, 0x31, 0x95, 0x0c, 0xb8, 0xb8, 0x12, 0x73, 0x72, 0xe2, 0xa1, 0x66, 0x28,
	0x71, 0x31, 0x07, 0xa4, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x09, 0xe8, 0xc1, 0x6c,
	0xd1, 0x83, 0x48, 0x07, 0x81, 0x24, 0x93, 0xd8, 0xc0, 0x42, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x0e, 0x81, 0x9a, 0x98, 0x00, 0x00, 0x00,
}
